# This is a basic workflow to help you get started with Actions

name: CI-develop

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: hse-prod

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |          
          docker build -t covidrisk-dev .
          
  deploy:
    runs-on: hse-prod      
    needs: build
    steps:
      - name: deploy master
        run: |
          docker container rm -f covidcontainer-dev || true 
          docker run -d --name covidcontainer-dev -p 3839:3838 covidrisk-dev  
